[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "michat"
version = "0.1.0"

[dependencies]
bytes = "0.2.10"
clap = "1.4.5"
env_logger = "0.5.13"
log = "^0.4"
mio = "0.6.16"
slab = "0.4.1"
failure = "0.1.2"