[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "michat"
version = "0.1.0"

[dependencies]
bytes = "0.4.12"
clap = "2.33.0"
env_logger = "0.7.0"
log = "^0.4"
mio = "0.6.19"
slab = "0.4.2"
failure = "0.1.5"