[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "michat"
version = "0.1.0"

[dependencies]
bytes = "0.4.12"
clap = "1.4.5"
env_logger = "0.6.1"
log = "^0.4"
mio = "0.6.19"
slab = "0.4.2"
failure = "0.1.5"